### ISSUE TITLE
Add Sorting for reviews by Rating

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-backend#2]
**Describe the solution you'd like**
Update the review get request endpoint to allowing sorting by Rating

**Comment by stephenmartin2951** [comment]
Would this functionality be added by modifying review.controller.ts?

**Comment by kellenwiltshire** [comment]
More so the review services as that's where the Sql calls are. Basically it'll be a param passed through to the `get` function just like the alphabetical or newest/oldest sorting.
