### ISSUE TITLE
Create new Stats endpoint

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-backend#42]
Create new `/stats` endpoint to query the DB

Should be a `GET` endpoint that accepts a query for start date and end date. It should get all reviews submitted between these 2 dates to return to frontend.

Should also return total lifetime reviews for overall, and by country.

**Comment by stephenmartin2951** [comment]
I'm traveling the next two weeks but if nobody picks this up by the time I'm back home I will take a look.

**Comment by kellenwiltshire** [comment]
No Worries, I forgot to assign myself. I am nearly done this task
